import argparse
import ast
import sys
from pysat.solvers import Glucose3

def solve_cnf_with_pysat(cnf_list):
    """
    使用 PySAT 的 Glucose3 求解器来验证 CNF 是否可满足
    """
    try:
        # 初始化求解器
        g = Glucose3()
        # 添加子句
        for clause in cnf_list:
            g.add_clause(clause)
        
        # 求解
        is_sat = g.solve()
        
        # 获取模型 (如果 SAT)
        model = g.get_model() if is_sat else None
        
        # 清理
        g.delete()
        
        return is_sat, model
    except Exception as e:
        print(f"PySAT Solver Error: {e}", file=sys.stderr)
        return None, None

def generate_standard_dataset(input_file, output_file):
    """
    读取包含 CNF 列表的文件，并使用 PySAT 计算标准答案，输出到新文件
    """
    try:
        with open(input_file, 'r', encoding='utf-8') as f_in, \
             open(output_file, 'w', encoding='utf-8') as f_out:
            
            f_out.write("# Standard SAT Dataset generated by PySAT (Glucose3)\n")
            f_out.write("# Format: CNF Formula :: SAT/UNSAT\n\n")
            
            for line_num, line in enumerate(f_in, 1):
                line = line.strip()
                if not line or line.startswith('#'):
                    # 保留注释和空行
                    f_out.write(line + "\n")
                    continue
                
                # 如果输入文件已经有 :: 分隔符，则只取前半部分
                if '::' in line:
                    cnf_str = line.split('::')[0].strip()
                else:
                    cnf_str = line
                
                try:
                    cnf_list = ast.literal_eval(cnf_str)
                    if not isinstance(cnf_list, list):
                        continue
                        
                    is_sat, _ = solve_cnf_with_pysat(cnf_list)
                    
                    if is_sat is True:
                        f_out.write(f"{cnf_str} :: SAT\n")
                        print(f"Processed line {line_num}: SAT")
                    elif is_sat is False:
                        f_out.write(f"{cnf_str} :: UNSAT\n")
                        print(f"Processed line {line_num}: UNSAT")
                    else:
                        f_out.write(f"# Error processing {cnf_str}\n")
                        
                except Exception as e:
                    print(f"Error parsing line {line_num}: {e}")
                    f_out.write(f"# Error parsing line {line_num}\n")
                    
        print(f"\nSuccessfully generated standard dataset at: {output_file}")
    except Exception as e:
        print(f"File IO Error: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="使用 PySAT 生成标准 SAT 测试集")
    parser.add_argument("-i", "--input", required=True, help="输入文件 (包含 CNF 列表，每行一个)")
    parser.add_argument("-o", "--output", required=True, help="输出文件 (标准数据集)")
    
    args = parser.parse_args()
    generate_standard_dataset(args.input, args.output)
